import { StatDefinition } from 'src/app/models/stat-definitions.model';

export const overallStatDefinitions: StatDefinition[] = [
  { label: 'Games', key: 'totalGames', id: 'totalGames' },
  {
    label: 'Perfect games',
    key: 'perfectGameCount',
    id: 'perfectGameCount',
    toolTip: 'A perfect game means every frame is filled with strikes.',
    prevKey: 'perfectGameCount',
  },
  {
    label: 'Clean games',
    key: 'cleanGameCount',
    id: 'cleanGameCount',
    toolTip: 'A clean game means every frame is filled with either a strike or a spare.',
    prevKey: 'cleanGameCount',
  },
  {
    label: 'Clean game percentage',
    key: 'cleanGamePercentage',
    id: 'cleanGamePercentage',
    isPercentage: true,
    toolTip: 'The percentage of how many games were clean games.',
    prevKey: 'cleanGamePercentage',
  },
  { label: 'Average', key: 'averageScore', id: 'averageScore', prevKey: 'averageScore' },
  { label: 'High game', key: 'highGame', id: 'highGame' },
  { label: 'Total pins', key: 'totalPins', id: 'totalPins' },
  { label: 'First ball average', key: 'averageFirstCount', id: 'averageFirstCount', prevKey: 'averageFirstCount' },
  {
    label: 'Strike-percentage',
    key: 'strikePercentage',
    id: 'strikePercentage',
    isPercentage: true,
    toolTip: 'This is the strike probability, calculated as the percentage of strikes you achieve out of a maximum of 12 per game.',
    prevKey: 'strikePercentage',
  },
  {
    label: 'Spare-percentage',
    key: 'overallSpareRate',
    id: 'sparePercentage',
    isPercentage: true,
    toolTip: 'This is the probability of how likely you hit a spare if your first throw was not a strike.',
    prevKey: 'overallSpareRate',
  },
  {
    label: 'Open-percentage',
    key: 'overallMissedRate',
    id: 'openPercentage',
    isPercentage: true,
    toolTip: 'This is the probability of how likely you miss a spare if your first throw was not a strike.',
    prevKey: 'overallMissedRate',
  },
];

export const seriesStatDefinitions: StatDefinition[] = [
  { label: 'Average 3-series score', key: 'average3SeriesScore', id: 'average3SeriesScore', prevKey: 'average3SeriesScore' },
  { label: 'High 3-series', key: 'high3Series', id: 'high3Series' },
  { label: 'Average 4-series score', key: 'average4SeriesScore', id: 'average4SeriesScore', prevKey: 'average4SeriesScore' },
  { label: 'High 4-series', key: 'high4Series', id: 'high4Series' },
  { label: 'Average 5-series score', key: 'average5SeriesScore', id: 'average5SeriesScore', prevKey: 'average5SeriesScore' },
  { label: 'High 5-series', key: 'high5Series', id: 'high5Series' },
  { label: 'Average 6-series score', key: 'average6SeriesScore', id: 'average6SeriesScore', prevKey: 'average6SeriesScore' },
  { label: 'High 6-series', key: 'high6Series', id: 'high6Series' },
];
export const leagueStatDefinitions: StatDefinition[] = [
  { label: 'Games', key: 'totalGames', id: 'league-totalGames' },
  {
    label: 'Perfect games',
    key: 'perfectGameCount',
    id: 'league-perfectGameCount',
    toolTip: 'A perfect game means every frame is filled with strikes.',
  },
  {
    label: 'Clean games',
    key: 'cleanGameCount',
    id: 'league-cleanGameCount',
    toolTip: 'A clean game means every frame is filled with either a strike or a spare.',
  },
  {
    label: 'Clean game percentage',
    key: 'cleanGamePercentage',
    id: 'league-cleanGamePercentage',
    isPercentage: true,
    toolTip: 'The percentage of how many games were clean games.',
    prevKey: 'cleanGamePercentage',
  },
  { label: 'Average', key: 'averageScore', id: 'league-averageScore', prevKey: 'averageScore' },
  { label: 'High game', key: 'highGame', id: 'league-highGame' },
  { label: 'Total pins', key: 'totalPins', id: 'league-totalPins' },
  { label: 'First ball average', key: 'averageFirstCount', id: 'league-averageFirstCount', prevKey: 'averageFirstCount' },
  { label: 'Total strikes', key: 'totalStrikes', id: 'league-totalStrikes' },
  { label: 'Strikes per game', key: 'averageStrikesPerGame', id: 'league-averageStrikesPerGame', prevKey: 'averageStrikesPerGame' },
  {
    label: 'Strike-percentage',
    key: 'strikePercentage',
    id: 'league-strikePercentage',
    isPercentage: true,
    toolTip: 'This shows your strike probability, calculated as the percentage of strikes you achieve out of a maximum of 12 per game.',
    prevKey: 'strikePercentage',
  },
  { label: 'Total spares', key: 'totalSpares', id: 'league-totalSpares' },
  { label: 'Spares per game', key: 'averageSparesPerGame', id: 'league-averageSparesPerGame', prevKey: 'averageSparesPerGame' },
  {
    label: 'Spare-percentage',
    key: 'overallSpareRate',
    id: 'league-sparePercentage',
    isPercentage: true,
    toolTip: 'This is the probability of how likely you hit a spare if your first throw was not a strike.',
    prevKey: 'overallSpareRate',
  },
  { label: 'Total opens', key: 'totalSparesMissed', id: 'totalSparesMissed' },
  { label: 'Opens per game', key: 'averageOpensPerGame', id: 'league-averageOpensPerGame', prevKey: 'averageOpensPerGame' },
  {
    label: 'Open-percentage',
    key: 'overallMissedRate',
    id: 'league-openPercentage',
    isPercentage: true,
    toolTip: 'This is the probability of how likely you miss a spare if your first throw was not a strike.',
    prevKey: 'overallMissedRate',
  },
];

export const throwStatDefinitions: StatDefinition[] = [
  { label: 'Total strikes', key: 'totalStrikes', id: 'totalStrikes' },
  { label: 'Strikes per game', key: 'averageStrikesPerGame', id: 'averageStrikesPerGame', prevKey: 'averageStrikesPerGame' },
  { label: 'Total spares', key: 'totalSpares', id: 'totalSpares' },
  { label: 'Spares per game', key: 'averageSparesPerGame', id: 'averageSparesPerGame', prevKey: 'averageSparesPerGame' },
  { label: 'Total opens', key: 'totalSparesMissed', id: 'totalSparesMissed' },
  { label: 'Opens per game', key: 'averageOpensPerGame', id: 'averageOpensPerGame', prevKey: 'averageOpensPerGame' },
];
export const sessionStatDefinitions: StatDefinition[] = [
  { label: 'Games', key: 'totalGames', id: 'sessionTotalGames' },
  {
    label: 'Perfect games',
    key: 'perfectGameCount',
    id: 'sessionPerfectGameCount',
    toolTip: 'A perfect game means every frame is filled with strikes.',
  },
  {
    label: 'Clean games',
    key: 'cleanGameCount',
    id: 'sessionCleanGameCount',
    toolTip: 'A clean game means every frame is filled with either a strike or a spare.',
  },
  {
    label: 'Clean game percentage',
    key: 'cleanGamePercentage',
    id: 'sessionCleanGamePercentage',
    isPercentage: true,
    toolTip: 'The percentage of how many games were clean games.',
    prevKey: 'cleanGamePercentage',
  },
  { label: 'Average', key: 'averageScore', id: 'sessionAverage', prevKey: 'averageScore' },
  { label: 'High game', key: 'highGame', id: 'sessionHighGame' },
  { label: 'Low game', key: 'lowGame', id: 'sessionLowGame' },
  { label: 'Total pins', key: 'totalPins', id: 'sessionTotalPins' },
  { label: 'First ball average', key: 'averageFirstCount', id: 'sessionAverageFirstCount', prevKey: 'averageFirstCount' },
  { label: 'Total strikes', key: 'totalStrikes', id: 'sessionTotalStrikes' },
  { label: 'Strikes per game', key: 'averageStrikesPerGame', id: 'sessionAverageStrikesPerGame', prevKey: 'averageStrikesPerGame' },
  {
    label: 'Strike-percentage',
    key: 'strikePercentage',
    id: 'sessionStrikePercentage',
    isPercentage: true,
    toolTip: 'This shows your strike probability, calculated as the percentage of strikes you achieve out of a maximum of 12 per game.',
    prevKey: 'strikePercentage',
  },
  { label: 'Total spares', key: 'totalSpares', id: 'sessionTotalSpares' },
  { label: 'Spares per game', key: 'averageSparesPerGame', id: 'sessionAverageSparesPerGame', prevKey: 'averageSparesPerGame' },
  {
    label: 'Spare-percentage',
    key: 'overallSpareRate',
    id: 'sessionSparePercentage',
    isPercentage: true,
    toolTip: 'This is the probability of how likely you hit a spare if your first throw was not a strike.',
    prevKey: 'overallSpareRate',
  },
  { label: 'Total opens', key: 'totalSparesMissed', id: 'sessionTotalSparesMissed' },
  { label: 'Opens per game', key: 'averageOpensPerGame', id: 'sessionAverageOpensPerGame', prevKey: 'averageOpensPerGame' },
  {
    label: 'Open-percentage',
    key: 'overallMissedRate',
    id: 'sessionOpenPercentage',
    isPercentage: true,
    toolTip: 'This is the probability of how likely you miss a spare if your first throw was not a strike.',
    prevKey: 'overallMissedRate',
  },
];
